'''
Problem 2
=========
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.

'''
n1 = 1
n2 = 2
fib = [n1, n2]
four_million = 4000000
sum_of_even = 0

while True:
    fib_n = fib[-1] + fib[-2]
    if fib_n <= four_million:
        fib.append(fib_n)
    else:
        break

# Add up all the even values in fib
for item in fib:
    if item % 2 == 0:
        sum_of_even += item
print(sum_of_even)
